site_name: TBI Lab Documentation
nav:
  - Login: login.md
  - Home: index.md
  - Roybal: roybal.md
repo_url: https://github.com/HypeFish/tbi-docs.git
theme:
  name: readthedocs
  custom_dir: docs/theme

extra_javascript:
  - /js/custom_login.js
  