site_name: TBI Lab Documentation
site_url: https://cnelabneu.github.io/
nav:
  - Login: login.md
  - Home: index.md
  - General: 
    - EEG: eeg.md
    - MRI: mri.md
  - Study:
    - Roybal: roybal.md
    - techs: techs.md


repo_url: https://github.com/cnelabneu/tbi-docs.git
use_directory_urls: false

theme:
  name: readthedocs
  custom_dir: docs/theme

extra_javascript:
  - js/custom_login.js


